services:
  mongo:
    image: mongo:7
    container_name: booking-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ./backend/BookingApi
    container_name: booking-api
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - MongoDb__ConnectionString=mongodb://mongo:27017
      - MongoDb__DatabaseName=bookingdb

  frontend:
    build:
      context: ./frontend
    container_name: booking-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
