apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-backend
  template:
    metadata:
      labels:
        app: booking-backend
    spec:
      containers:
        - name: booking-backend
          image: ghcr.io/dyinae/booking-backend:1.0
          ports:
            - containerPort: 8080
          env:
            - name: MongoDb__ConnectionString
              value: mongodb://mongodb:27017
            - name: MongoDb__DatabaseName
              value: bookingdb