apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-frontend
  template:
    metadata:
      labels:
        app: booking-frontend
    spec:
      containers:
        - name: booking-frontend
          image: ghcr.io/dyinae/gde_alk_fej_tech-frontend:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
