name: Build and Push Docker Images

on:
  push:
    branches:
      - dev
    paths-ignore:
      - 'k8s/backend-deployment.yaml'
      - 'k8s/frontend-deployment.yaml'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set version
        run: echo "VERSION=1.0.${{ github.run_number }}" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # backend

      - name: Build backend image
        run: |
          docker build -t ghcr.io/dyinae/gde_alk_fej_tech-backend:${{ env.VERSION }} ./backend/BookingApi

      - name: Push backend image
        run: |
          docker push ghcr.io/dyinae/gde_alk_fej_tech-backend:${{ env.VERSION }}

      - name: Update backend deployment image
        run: |
          sed -i "s|image: ghcr.io/dyinae/gde_alk_fej_tech-backend:.*|image: ghcr.io/dyinae/gde_alk_fej_tech-backend:${{ env.VERSION }}|" k8s/backend-deployment.yaml

      # front

      - name: Build frontend image
        run: |
          docker build -t ghcr.io/dyinae/gde_alk_fej_tech-frontend:${{ env.VERSION }} ./frontend

      - name: Push frontend image
        run: |
          docker push ghcr.io/dyinae/gde_alk_fej_tech-frontend:${{ env.VERSION }}

      - name: Update frontend deployment image
        run: |
          sed -i "s|image: ghcr.io/dyinae/gde_alk_fej_tech-frontend:.*|image: ghcr.io/dyinae/gde_alk_fej_tech-frontend:${{ env.VERSION }}|" k8s/frontend-deployment.yaml

      # commitolok vissza

      - name: Commit updated deployments
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add k8s/backend-deployment.yaml
          git add k8s/frontend-deployment.yaml
          git commit -m "Auto update image tag to ${{ env.VERSION }}" || echo "No changes to commit"
          git push