name: Build and Push Docker Images

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build backend image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/backend:latest ./backend/BookingApi

      - name: Push backend image
        run: |
          docker push ghcr.io/${{ github.repository }}/backend:latest

      - name: Build frontend image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/frontend:latest ./frontend

      - name: Push frontend image
        run: |
          docker push ghcr.io/${{ github.repository }}/frontend:latest